"""
Command line: derivgen generate | check | build | bench

    python -m derivgen generate "Remove the safety features"
    python -m derivgen check memory/derivatives/d001_no_safety/child.tcl
    python -m derivgen build memory/platforms/derivsense.tcl -o out/parent.v
    python -m derivgen bench
"""

import argparse
import json
import sys
from pathlib import Path

from .build import build_verilog
from .check import check, errors, format_problems
from .compare import compare
from .edits import Edit, EditError, apply_edits
from .library import read_library
from .plan import plan_llm, plan_rules
from .retrieve import load_derivatives
from .tcl import read_tcl_file, write_tcl

ROOT = Path(__file__).parent.parent
LIBRARY_DIR = ROOT / "memory" / "ip_library"
PLATFORM_DIR = ROOT / "memory" / "platforms"
DERIVATIVE_DIR = ROOT / "memory" / "derivatives"
CACHE_DIR = ROOT / "memory" / "llm_cache"


def _load(parent_name: str):
    design = read_tcl_file(PLATFORM_DIR / f"{parent_name}.tcl")
    return design, read_library(LIBRARY_DIR)


def _make_plan(args, instruction, parent, library, name, exclude=None):
    if args.planner == "rules":
        return plan_rules(instruction, parent, library, name)
    from .llm import make_backend
    backend = make_backend(args.llm, CACHE_DIR, ROOT / "out")
    return plan_llm(instruction, parent, library, name, backend,
                    past=load_derivatives(DERIVATIVE_DIR), exclude_case=exclude)


# ---------------------------------------------------------------------------
# generate
# ---------------------------------------------------------------------------

def cmd_generate(args) -> int:
    parent, library = _load(args.parent)
    name = args.name or f"{args.parent}_derivative"

    plan = _make_plan(args, args.instruction, parent, library, name)

    print(f'instruction : "{args.instruction}"')
    print(f"planner     : {args.planner}")
    print()
    print("how it decided:")
    for line in plan.trace:
        print(f"  {line}")
    print()

    if plan.error:
        print("ERROR (the tool broke; this is not a verdict on the request)")
        print(f"  {plan.error}")
        return 3
    if not plan.ok:
        print("REFUSED")
        print(f"  {plan.refused}")
        return 2

    print("edits:")
    for edit in plan.edits:
        print(f"  {edit.describe()}")
        if edit.reason:
            print(f"      because {edit.reason}")
    print()

    design = apply_edits(parent, plan.edits, name).design
    problems = check(design, library)
    print("check:")
    print(format_problems(problems))
    if errors(problems):
        return 2

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{name}.tcl").write_text(write_tcl(design), encoding="utf-8")
    (out_dir / "edits.json").write_text(
        json.dumps([e.to_dict() for e in plan.edits], indent=2) + "\n",
        encoding="utf-8",
    )
    verilog = build_verilog(
        design, library,
        f"generated by DerivGen from {args.parent}.tcl\ninstruction: {args.instruction}",
    )
    (out_dir / f"{name}.v").write_text(verilog, encoding="utf-8")

    print()
    print(f"wrote {out_dir / (name + '.tcl')}")
    print(f"wrote {out_dir / 'edits.json'}")
    print(f"wrote {out_dir / (name + '.v')}  ({len(verilog.splitlines())} lines)")
    return 0


# ---------------------------------------------------------------------------
# check / build
# ---------------------------------------------------------------------------

def cmd_check(args) -> int:
    design = read_tcl_file(args.script)
    library = read_library(LIBRARY_DIR)
    problems = check(design, library)
    print(f"{design.name}: {len(design.instances)} instances")
    print(format_problems(problems))
    return 2 if errors(problems) else 0


def cmd_build(args) -> int:
    design = read_tcl_file(args.script)
    library = read_library(LIBRARY_DIR)
    problems = errors(check(design, library))
    if problems:
        print("refusing to build: the design does not check out")
        print(format_problems(problems))
        return 2
    verilog = build_verilog(design, library,
                            f"generated by DerivGen from {Path(args.script).name}")
    if args.out:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out).write_text(verilog, encoding="utf-8")
        print(f"wrote {args.out}  ({len(verilog.splitlines())} lines)")
    else:
        print(verilog)
    return 0


# ---------------------------------------------------------------------------
# bench
# ---------------------------------------------------------------------------

def cmd_bench(args) -> int:
    library = read_library(LIBRARY_DIR)
    records = load_derivatives(DERIVATIVE_DIR)
    if not records:
        print(f"no derivative records found in {DERIVATIVE_DIR}")
        return 1

    rows: list[dict] = []

    for record in records:
        parent = read_tcl_file(PLATFORM_DIR / f"{record.parent}.tcl")
        case_dir = DERIVATIVE_DIR / record.case_id
        raw = json.loads((case_dir / "record.json").read_text(encoding="utf-8"))

        # -- oracle mode: replay the stored edits ------------------------
        golden_path = case_dir / raw.get("child_tcl", "")
        if raw.get("child_tcl") and golden_path.exists():
            golden = read_tcl_file(golden_path)
            try:
                edits = [Edit.from_dict(e) for e in record.edits]
                design = apply_edits(parent, edits, golden.name).design
                result = compare(design, golden)
                rows.append({
                    "case": record.case_id, "mode": "oracle",
                    "instruction": "(stored edits)",
                    "f1": result.overall_f1, "pass": result.perfect,
                    "detail": "" if result.perfect else "differs from golden",
                })
            except EditError as err:
                rows.append({"case": record.case_id, "mode": "oracle",
                             "instruction": "(stored edits)", "f1": 0.0,
                             "pass": False, "detail": str(err)})

            # -- planner mode: one row per paraphrase --------------------
            for instruction in raw.get("paraphrases", [record.instruction]):
                plan = _make_plan(args, instruction, parent, library,
                                  golden.name, exclude=record.case_id)
                if not plan.ok:
                    why = (plan.error or plan.refused).splitlines()[0]
                    label = "error" if plan.error else "refused"
                    rows.append({"case": record.case_id, "mode": args.planner,
                                 "instruction": instruction, "f1": 0.0,
                                 "pass": False, "error": bool(plan.error),
                                 "detail": f"{label}: {why}"})
                    continue
                design = apply_edits(parent, plan.edits, golden.name).design
                result = compare(design, golden)
                rows.append({
                    "case": record.case_id, "mode": args.planner,
                    "instruction": instruction,
                    "f1": result.overall_f1, "pass": result.perfect,
                    "detail": "" if result.perfect else _first_difference(result),
                })

        # -- instructions that must be refused ---------------------------
        for instruction in raw.get("must_refuse", []):
            plan = _make_plan(args, instruction, parent, library,
                              "should_not_exist", exclude=record.case_id)
            # plan.declined, not plan.ok: an API timeout produces no edits
            # too, and that must not be scored as a correct refusal.
            correct = plan.declined
            if plan.error:
                detail = "error: " + plan.error.splitlines()[0]
            elif correct:
                detail = ""
            else:
                detail = "accepted, but should have refused"
            rows.append({
                "case": record.case_id, "mode": args.planner + "/refuse",
                "instruction": instruction,
                "f1": 1.0 if correct else 0.0,
                "pass": correct, "error": bool(plan.error),
                "detail": detail,
            })

    # -- report ----------------------------------------------------------
    print()
    print(f"{'case':<20}{'mode':<16}{'F1':>6}  {'':<4}instruction")
    print("-" * 100)
    for row in rows:
        mark = "ok  " if row["pass"] else "FAIL"
        print(f"{row['case']:<20}{row['mode']:<16}{row['f1']:>6.3f}  "
              f"{mark} {row['instruction'][:48]}")
        if row["detail"]:
            print(f"{'':<42}  -> {row['detail'][:70]}")
    print("-" * 100)

    for mode in sorted({r["mode"] for r in rows}):
        group = [r for r in rows if r["mode"] == mode]
        passed = sum(1 for r in group if r["pass"])
        mean = sum(r["f1"] for r in group) / len(group)
        print(f"{mode:<16} {passed}/{len(group)} passed, mean F1 {mean:.3f}")

    total_passed = sum(1 for r in rows if r["pass"])
    print()
    print(f"TOTAL {total_passed}/{len(rows)} passed")

    if args.json:
        Path(args.json).parent.mkdir(parents=True, exist_ok=True)
        Path(args.json).write_text(json.dumps(rows, indent=2) + "\n",
                                   encoding="utf-8")
        print(f"wrote {args.json}")

    # What counts as failure: oracle mode and the refusals must be perfect,
    # because those test the machinery. How many paraphrases the planner gets
    # is a measurement, not a regression -- it is the number we are trying to
    # move. Use --strict to fail on those too.
    errored = [r for r in rows if r.get("error")]
    if errored:
        print(f"{'(errors)':<16} {len(errored)} row(s) never got an answer "
              f"(network, quota or a bad reply) and are scored 0")

    must_pass = [r for r in rows
                 if r["mode"] == "oracle" or r["mode"].endswith("/refuse")]
    broken = [r for r in must_pass if not r["pass"] and not r.get("error")]
    if broken:
        print()
        print(f"FAILED: {len(broken)} oracle/refusal case(s) broke. "
              f"The machinery is wrong, not just the planner.")
        return 1
    if errored:
        print()
        print("INCOMPLETE: some rows never got an answer, so this run is not "
              "a fair score. Nothing is known to be broken.")
        return 1
    if args.strict and total_passed != len(rows):
        return 1
    return 0


def _first_difference(result) -> str:
    for score in result.scores:
        if score.missing:
            return f"missing {score.name[:-1]} {min(score.missing)}"
        if score.extra:
            return f"extra {score.name[:-1]} {min(score.extra)}"
    return "differs"


# ---------------------------------------------------------------------------

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="derivgen")
    parser.add_argument("--parent", default="derivsense",
                        help="parent platform in memory/platforms")
    parser.add_argument("--planner", choices=("rules", "llm"), default="rules")
    parser.add_argument("--llm", choices=("mock", "manual", "anthropic", "gemini"), default="mock",
                        help="where the language model lives, if --planner llm")
    sub = parser.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate", help="plan and build a derivative")
    gen.add_argument("instruction")
    gen.add_argument("--name", help="name for the derivative")
    gen.add_argument("--out", default="out")
    gen.set_defaults(func=cmd_generate)

    chk = sub.add_parser("check", help="check a platform script")
    chk.add_argument("script")
    chk.set_defaults(func=cmd_check)

    bld = sub.add_parser("build", help="turn a script into Verilog")
    bld.add_argument("script")
    bld.add_argument("-o", "--out")
    bld.set_defaults(func=cmd_build)

    ben = sub.add_parser("bench", help="run every case in memory/derivatives")
    ben.add_argument("--json", help="also write the rows to this file")
    ben.add_argument("--strict", action="store_true",
                     help="fail if any planner paraphrase misses, not just "
                          "the oracle and refusal cases")
    ben.set_defaults(func=cmd_bench)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
